### ISSUE TITLE
should 'history' be enabled by default?

### ISSUE THREAD

**Issue by JustinAzoff** [joshmarshall/jsonrpclib#47]
This is basically the same issue as #46.

I too "fixed" the memory leak by adding calls to history.clear().  As far as I can tell the history code is only used for the tests, and the fact that it is enabled by default is likely causing memory leaks for anyone using this library.

Is there any reason the history code couldn't be behind an enable_history=False parameter to ServerProxy ?

**Comment by joshmarshall** [comment]
Hi Justin --

I've thought about this and agree that it shouldn't be on by default, but I worry that turning it completely off might break existing usage (however rare it is used). So we'd either need to increment a major (backwards-incompatible) release, or alternatively "fix" the bug by putting a cap on history size (say 50 entries) and simply truncating it automatically, so it never grows beyond a small memory footprint.

Thoughts?

**Comment by JustinAzoff** [comment]
Capping to 50 by default could work.  If it had done that, I likely never would have noticed a problem.. I was seeing 20G+ memory usage after about a week.. likely millions of cached responses.

There might be some use cases where even 50 may be too much.  I could see someone hitting an API that returns a very large (20M or so) response.  50 of those is almost a gigabyte.

If backwards compatibility is a concern, having the parameter be enable_history=True by default could be an option.

I tried searching for projects on github that used jsonrpclib to see how they are using it, but the majority of the results are projects containing jsonrpclib itself.  Probably a way to filter this down a bit using the API.

**Comment by joshmarshall** [comment]
Opened a PR for the fix. Due to the way the history works -- it's a global singleton, not a great choice in the first place :( -- I can't necessarily make it a constructor argument for ServerProxy because constructing multiple instances with different values would flatten the previous ones. This way, it is configured globally -- `history.size = 0` means no history, `history.size < 0` means unlimited history, and `history.size > 0` means fixed history. It defaults to 20 entries for both requests and responses.

Thoughts?

**Comment by joshmarshall** [comment]
Should be resolved in 0.1.7+
